# pylint: disable=C0111
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

# Autogenerated config.py
config.load_autoconfig(False)
config.source("./themes/onedark.py")
c.search.wrap = False
c.new_instance_open_target = "tab-bg"
c.new_instance_open_target_window = "last-focused"
c.qt.args = [
    "ignore-gpu-blacklist",
    "enable-gpu-rasterization",
    "enable-native-gpu-memory-buffers",
    "enable-zero-copy",
    "gtk-version=4",
    "enable-features=VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization,VaapiIgnoreDriverChecks,PlatformHEVCDecoderSupport,UseMultiPlaneFormatForHardwareVideo",
    "num-raster-threads=4",
    "use-gl desktop",
    "enable-accelerated-2d-canvas",
    "enable-accelerated-video-decode",
    "disable-gpu-sandbox",
    "content.prefers_reduced_motion",
]
c.qt.workarounds.disable_accelerated_2d_canvas = "never"
c.content.autoplay = False
config.set("content.cookies.accept", "all", "chrome-devtools://*")
config.set("content.cookies.accept", "all", "devtools://*")
config.set("content.headers.accept_language", "", "https://matchmaker.krunker.io/*")
c.content.headers.user_agent = "Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version_short} Safari/{webkit_version}"
config.set("content.javascript.enabled", True, "chrome-devtools://*")
config.set("content.javascript.enabled", True, "devtools://*")
config.set("content.javascript.enabled", True, "chrome://*/*")
config.set("content.javascript.enabled", True, "qute://*/*")
config.set(
    "content.local_content_can_access_remote_urls",
    True,
    "file:///home/whammou/.local/share/qutebrowser/userscripts/*",
)
config.set(
    "content.local_content_can_access_file_urls",
    False,
    "file:///home/whammou/.local/share/qutebrowser/userscripts/*",
)
c.content.user_stylesheets = "~/.config/qutebrowser/css/custom.css"
c.downloads.location.directory = "/home/whammou/Downloads/"
c.completion.open_categories = [
    "searchengines",
    "quickmarks",
    "bookmarks",
    "filesystem",
]
c.hints.border = "0px"
c.hints.radius = 0
c.input.links_included_in_focus_chain = False
c.scrolling.bar = "when-searching"
c.scrolling.smooth = False
c.statusbar.show = "never"
c.tabs.select_on_remove = "prev"
c.tabs.show = "multiple"
c.tabs.tabs_are_windows = True
c.url.default_page = "https://ascii-start.customstart.page/"
c.url.searchengines = {
    "DEFAULT": "https://opnxng.com/search?q={}",
    "gs": "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q={}&btnG=",
    "g": "https://www.google.com/search?q={}",
    "b": "https://search.brave.com/search?q={}",
    "y": "https://www.youtube.com/results?search_query={}",
    "wa": "https://wiki.archlinux.org/?search={}",
    "lg": "https://libgen.li/index.php?req={}",
}
c.url.start_pages = ["https://ascii-start.customstart.page/"]
c.colors.webpage.preferred_color_scheme = "dark"
c.colors.webpage.darkmode.enabled = True
# c.fonts.default_size = "13pt"
c.fonts.web.size.default = 19

# Bindings for normal mode
c.aliases["split"] = "spawn _qtile_spawn_split_y"
c.aliases["vsplit"] = "spawn _qtile_spawn_split_x"
c.aliases["tab"] = "spawn _qtile_spawn_tab"
c.aliases["tab_new"] = "spawn _qtile_spawn_new_tab"
c.aliases["screen"] = "spawn _qtile_spawn_screen"
# Medias

config.unbind("d")
config.unbind("D")
config.bind("M", "hint links spawn mpv --x11-name='mpv-preview' {hint-url}")

# Navigation
config.bind("m", "mode-enter set_mark")

# Qtile
config.unbind("F")
config.bind(
    "Fv",
    "hint links spawn qtile cmd-obj -o layout -f spawn_split -a 'qb {hint-url}' x",
)
config.bind(
    "Fx",
    "hint links spawn qtile cmd-obj -o layout -f spawn_split -a 'qb {hint-url}' y",
)
config.bind(
    "Ft",
    "hint links spawn qtile cmd-obj -o layout -f spawn_tab -a 'qb {hint-url}'",
)
config.bind(
    "FT",
    "hint links spawn _qtile_spawn_new_tab '{hint-url}'",
)
config.bind(
    "Ff",
    "hint links spawn qtile cmd-obj -o root -f spawn -a 'qb {hint-url}'",
)
config.bind("X", "cmd-set-text -s :split")
config.bind("V", "cmd-set-text -s :vsplit", mode="normal")
config.bind("T", "cmd-set-text -s :tab")
config.bind("<Ctrl-T>", "cmd-set-text -s :tab_new")

# Settings
config.bind("xb", "config-cycle statusbar.show never always")
config.bind(
    "xc",
    "config-cycle content.user_stylesheets ~/.config/qutebrowser/css/default.css ~/.config/qutebrowser/css/custom.css",
)
config.bind("xt", "config-cycle tabs.show multiple always")
