enable_selector = true
selector = "rofi -dmenu -i -p 'Open with: '"
term_exec_args = ""
expand_wildcards = true

[[handlers]]
exec = "mpv --profile=image %u"
terminal = false
regexes = [
  'https?:\/\/[^\s\/$.?#].[^\s]*\.(?:png|jpe?g|gif|svg|webp|bmp|tiff|svg)$'
]

[[handlers]]
exec = "handlr launch .mkv %u"
terminal = false
regexes = ['https?:\/\/[^\s\/$.?#].[^\s]*\.(?:mp4|mkv)$']

[[handlers]]
exec = "nvim %u"
terminal = true
regexes = ['scp?:\/\/[^\s\/$.?#].[^\s]*']

[[handlers]]
exec = 'sh -c "exec nvim \"$(echo \"$1\" | sed \"s,https://,davs://,\")\"" sh %u'
terminal = true
regexes = ['^https://[^\s/]+/.*\.org(?:\?[^\s]*)?(?:\#[^\s]*)?$']

# [[handlers]]
# exec = "zapdf %u"
# terminal = false
# regexes = [
#  'https?:\/\/[^\s]+\.pdf(?:\?[^\s]*)?(?:\#[^\s]*)?',
#  'file:\/\/[^\s]+\.pdf(?:\?[^\s]*)?(?:\#[^\s]*)?',
#  '^\/.*\.pdf(?:\?[^\s]*)?(?:\#[^\s]*)?$',
# ]

[[handlers]]
exec = "handlr launch .mkv %u"
terminal = false
regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.']

[[handlers]]
exec = "orgmode-open-id %u"
terminal = true
regexes = ["^id:"]

[[handlers]]
exec = "neomutt %u"
terminal = true
regexes = ['^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$']

# [[handlers]]
# exec = "mpv --x11-name='mpv-float' %u"
# terminal = false
# regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.*#__preview']

[[handlers]]
exec = "handlr launch .docx %u"
terminal = false
regexes = [
  'https?:\/\/[^\s]+\.(abw|csv|dbf|dif|djvu|doc|docm|docx|dot|dotm|dotx|epub|fodg|fodp|fods|fodt|gnumeric|htm|html|json|mml|mobi|odf|odg|odm|odp|ods|odt|otg|oth|otp|ots|ott|oxt|pot|potm|potx|ppsx|ppt|pptm|pptx|rtf|slk|sxc|sxi|t602|tsv|txt|typ|uos|uot|uof|wpd|xls|xlsb|xlsm|xlsx|xlt|xltm|xltx|xml|pdf)(?:\?[^\s]*)?(?:\#[^\s]*)?$',
  'file:\/\/[^\s]+\.(abw|csv|dbf|dif|djvu|doc|docm|docx|dot|dotm|dotx|epub|fodg|fodp|fods|fodt|gnumeric|htm|html|json|mml|mobi|odf|odg|odm|odp|ods|odt|otg|oth|otp|ots|ott|oxt|pot|potm|potx|ppsx|ppt|pptm|pptx|rtf|slk|sxc|sxi|t602|tsv|txt|typ|uos|uot|uof|wpd|xls|xlsb|xlsm|xlsx|xlt|xltm|xltx|xml|pdf)(?:\?[^\s]*)?(?:\#[^\s]*)?$',
  '^\/.*\.(abw|csv|dbf|dif|djvu|doc|docm|docx|dot|dotm|dotx|epub|fodg|fodp|fods|fodt|gnumeric|htm|html|json|mml|mobi|odf|odg|odm|odp|ods|odt|otg|oth|otp|ots|ott|oxt|pot|potm|potx|ppsx|ppt|pptm|pptx|rtf|slk|sxc|sxi|t602|tsv|txt|typ|uos|uot|uof|wpd|xls|xlsb|xlsm|xlsx|xlt|xltm|xltx|xml|pdf)(?:\?[^\s]*)?(?:\#[^\s]*)?$',
]
