[urgency_low]
timeout = 21
frame_color = "#e5c07b"
highlight = "#e5c07b"
format = "<b><span foreground='#e5c07b' >  %s</span></b>\n\n%b"

[urgency_normal]
timeout = 21
frame_color = "#56b6c2"
highlight = "#56b6c2"
format = "<b><span foreground='#56b6c2' >  %s</span></b>\n\n%b"

[urgency_critical]
timeout = 0
history_ignore = yes
frame_color = "#e86671"
highlight = "#e86671"
format = "<b><span foreground='#e86671' >  %s</span></b>\n\n%b"

# vim:foldmethod=marker
