[urgency_low]
timeout = 21
frame_color = "#efbd5d"
highlight = "#efbd5d"
format = "<b><span foreground='#efbd5d' >  %s</span></b>\n\n%b"

[urgency_normal]
timeout = 21
frame_color = "#34bfd0"
highlight = "#34bfd0"
format = "<b><span foreground='#34bfd0' >  %s</span></b>\n\n%b"

[urgency_critical]
timeout = 0
history_ignore = yes
frame_color = "#f65866"
highlight = "#f65866"
format = "<b><span foreground='#f65866' >  %s</span></b>\n\n%b"

# vim:foldmethod=marker
