[system]
appname = System
format = "<b><span foreground='#455574' >󰒓  %s</span></b>\n\n%b"
frame_color = "#455574"
highlight = "#455575"
set_stack_tag = string:x-dunst-stack-tag:system
history_ignore = yes
set_transient = yes
timeout = 3

# vim:foldmethod=marker
