#!/bin/sh
# shellcheck disable=SC2034
# ==============================================================================
# yt-x Theme Extension: OneDark Dark
# ==============================================================================

if $CLI_SUPPORTS_TRUE_COLOR && $CONFIG_ENABLE_COLORS; then
  # OneDark Dark: cyan (#56b6c2)
  THEME_FZF_ICON_COLOR_PRIMARY="$(printf '\033[38;2;86;182;194m')"

  # OneDark Dark: grey (#5c6370)
  THEME_FZF_ICON_COLOR_SECONDARY="$(printf '\033[38;2;92;99;112m')"

  # OneDark Dark: orange (#d19a66)
  THEME_FZF_ICON_COLOR_ACCENT="$(printf '\033[38;2;209;154;102m')"

  # OneDark Dark: red (#e86671)
  THEME_FZF_ICON_COLOR_ERROR="$(printf '\033[38;2;232;102;113m')"

  # OneDark Dark: fg (#abb2bf)
  THEME_FZF_PREVIEW_TITLE="$(printf '\033[38;2;171;178;191m')"

  # OneDark Dark: blue (#61afef)
  THEME_FZF_PREVIEW_KEY="$(printf '\033[38;2;97;175;239m')"

  # OneDark Dark: bg2 (#393f4a)
  THEME_FZF_PREVIEW_VALUE="$(printf '\033[38;2;92;99;112m')"

  # OneDark Dark: bg2 (#393f4a)
  THEME_FZF_PREVIEW_DIVIDER="$(printf '\033[38;2;57;63;74m')"

  # OneDark Dark: green (#98c379)
  THEME_PLAYER_START="$(printf '\033[38;2;152;195;121m')"

  THEME_BOLD="$(printf '\033[1m')"
  THEME_RESET="$(printf '\033[0m')"

  CONFIG_GUM_OPTS="--prompt.foreground #c678dd --indicator.foreground #c678dd --selected-indicator.foreground #c678dd --unselected-prefix.foreground #5c6370 --header.foreground #c678dd --text.foreground #abb2bf --cursor-text.foreground #abb2bf --match.foreground #c678dd --placeholder.foreground #5c6370 --prompt  > --indicator ◆ --selected-prefix  ◉  --unselected-prefix  ○  --placeholder こんにちは..."
  CONFIG_GUM_FILTER_OPTS="--prompt.foreground #c678dd --indicator.foreground #c678dd --selected-indicator.foreground #c678dd --unselected-prefix.foreground #5c6370 --header.foreground #c678dd --text.foreground #abb2bf --cursor-text.foreground #abb2bf --match.foreground #c678dd --placeholder.foreground #5c6370 --prompt  > --indicator ◆ --selected-prefix  ◉  --unselected-prefix  ○  --placeholder こんにちは..."
  CONFIG_GUM_INPUT_OPTS="--prompt.foreground #c678dd --cursor.foreground #abb2bf --placeholder こんにちは... --cursor.mode blink"
  CONFIG_GUM_PAGER_OPTS="--foreground #abb2bf --line-number.foreground #5c6370 --match.foreground #c678dd --match-highlight.foreground #21252b --match-highlight.background #c678dd --help.foreground #5c6370 --show-line-numbers --soft-wrap --border-foreground #c678dd"
  CONFIG_GUM_SPIN_OPTS="--spinner dot --spinner.foreground #c678dd --title.foreground #5c6370 --align left"
  CONFIG_GUM_CONFIRM_OPTS="--prompt.foreground #c678dd --selected.foreground #21252b --selected.background #c678dd --unselected.foreground #5c6370"

  CONFIG_FZF_OPTS="
  --layout=reverse
  --info=inline-right
  --highlight-line
  --no-scrollbar
  --no-margin
  --cycle
  --border=sharp
  --input-border=none
  --list-border=none
  --preview-border=none
  --preview-label-pos=0
  --list-border=none
  --header-border=none
  --footer-border=none
  --ansi
  --pointer='▌'
  --marker='▌'
  --bind=right:accept,left:abort,ctrl-/:toggle-preview,ctrl-space:toggle-wrap+toggle-preview-wrap
  --preview-window=border-line,right,40%,wrap,nohidden
  --bind='ctrl-z:abort'
  --bind='ctrl-u:half-page-up'
  --bind='ctrl-d:half-page-down'
  --bind='ctrl-x:jump'
  --bind='ctrl-f:preview-page-down'
  --bind='ctrl-b:preview-page-up'
  --bind='ctrl-q:select-all+accept'
  --bind='ctrl-a:beginning-of-line'
  --bind='ctrl-e:end-of-line'
  --bind='alt-a:toggle-all'
  --bind='alt-g:first,alt-G:last'
  --bind='f3:toggle-preview-wrap'
  --bind='f4:toggle-preview'
  --bind='shift-down:preview-page-down,shift-up:preview-page-up'
  --bind='alt-shift-down:preview-down,alt-shift-up:preview-up'
  --wrap
  --color=bg:#282c34
  --color=bg+:#323640
  --color=border:#565C66
  --color=fg:#abb2bf
  --color=gutter:#282c34
  --color=header:#abb2bf
  --color=hl+:#e86671
  --color=hl:#e86671
  --color=info:#565C66
  --color=marker:#e86671
  --color=pointer:#e86671
  --color=prompt:#61afef
  --color=query:#abb2bf:regular
  --color=scrollbar:#abb2bf
  --color=separator:#565C66
  --color=spinner:#e86671"
  export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $CONFIG_FZF_OPTS"
fi
