--bind change:top,ctrl-y:toggle-all+unix-line-discard+top,alt-k:preview-up,alt-j:preview-down
--color=bg+:#393f4a,bg:#282c34,spinner:green,hl:red
--color=fg:#abb2bf,header:red,info:blue,pointer:red
--color=marker:yellow,fg+:#abb2bf,prompt:blue,hl+:red
--color=selected-bg:#3b3f4c
--color=border:#5c6370
--border sharp --border-label="" --preview-window="sharp" --prompt="❯ "
--marker=" " --pointer="◆" --separator="─" --scrollbar="▎"
--multi
--cycle
--layout=reverse
--height=50%
--preview-window=wrap
