#!/usr/bin/env bash

# Send a substitute notification that contains actions
dunst_action=$(
  dunstify \
    -a "ntfy" \
    -A "accept, Accept incoming call" \
    -A "reject, Reject incoming call" \
    -h "string:x-dunst-stack-tag:call" \
    "$DUNST_SUMMARY Call" "$DUNST_BODY!"
)

# Define Actions
case $dunst_action in
"reject")
  curl \
    -H "t:Phone Action" \
    -H "p:min" \
    -d "!PHONE:REJECT" \
    whamlab.sytes.net/android-socket
  ;;
"accept")
  curl \
    -H "t:Phone Action" \
    -H "p:min" \
    -d "!PHONE:ACCEPT" \
    whamlab.sytes.net/android-socket
  ;;
esac
