#!/usr/bin/env bash

# Send a substitute notification that contains actions
dunst_action=$(dunstify -a "dis+$DUNST_APP_NAME" -A "yank,Yank Clipboard" "Clipboard" "$DUNST_BODY")

# Define Actions
case $dunst_action in
"yank")
  echo -n $DUNST_BODY | wl-copy
  ;;
esac
