#!/usr/bin/env sh

notificationTitle=$DUNST_SUMMARY
notificationBody=$DUNST_BODY

formatedBody=$(echo "$DUNST_BODY" | perl -pe 's/^(?!https?)([^:]*):/<b>$1<\/b>:/')

dunstify -c "ntfy" "$DUNST_SUMMARY" "$formatedBody"
