#!/usr/bin/env bash
# ~/.config/dunst/scripts/sound-dispatcher
# Dispatches different sounds based on notification details

# Available environment variables:
# DUNST_APP_NAME, DUNST_SUMMARY, DUNST_BODY, DUNST_ICON_PATH
# DUNST_URGENCY, DUNST_ID, DUNST_PROGRESS, DUNST_CATEGORY, DUNST_URLS

# Sound for test notifications
# if [[ "$DUNST_SUMMARY" == "test" ]]; then
#   paplay --volume=$VOLUME ~/.local/share/bell/alert-01.wav
#   exit 0
# fi

BELL_DIR=~/.local/share/bell
VOLUME=1.0

play_sound() {
  pw-play \
    --media-role="Notification" \
    --volume=$VOLUME \
    $BELL_DIR/"$1"
}

case "$DUNST_CATEGORY" in
ntfy-script)
  exit 0
  ;;
esac

case "$DUNST_SUMMARY" in
Beeper | Zalo)
  play_sound staplebops-02.wav
  exit 0
  ;;
Terminal | Clipboard | RemoteSession | OpencodeCode | Remote\ Warning)
  play_sound yup-01.wav
  exit 0
  ;;
Reminder | Orgmode)
  play_sound staplebops-04.wav
  exit 0
  ;;
Spark)
  play_sound bip-bop-10.wav
  exit 0
  ;;
Mpv | SimpMusic | Pocket\ Casts)
  exit 0
  ;;
esac

# Default sound for all other notifications
case "$DUNST_URGENCY" in
LOW) play_sound bip-bop-05.wav ;;
NORMAL) play_sound staplebops-01.wav ;;
CRITICAL) play_sound nope-03.wav ;;
esac
