return {
  --  {
  --    "nvim-telescope/telescope.nvim",
  --    ft = "org",
  --    dependencies = {
  --      -- your other telescope extensions
  --      -- ...
  --      {
  --        "jmbuhr/telescope-zotero.nvim",
  --        ft = "org",
  --        dependencies = {
  --          { "kkharji/sqlite.lua" },
  --        },
  --        opts = {
  --          -- File system options
  --          zotero_db_path = "~/Zotero/zotero.sqlite",
  --          better_bibtex_db_path = "~/Zotero/better-bibtex.sqlite",
  --          zotero_storage_path = "~/Zotero/storage",
  --          pdf_opener = nil,
  --
  --          -- Picker options
  --          picker = {
  --            with_icons = true,
  --            hlgroups = {
  --              icons = "SpecialChar",
  --              author_date = "Comment",
  --              title = "Title",
  --            },
  --          },
  --
  --          -- Filetype options (refer to next section)
  --          ft = { "org" },
  --        },
  --        -- options:
  --        -- to use the default opts:
  --        config = function() end,
  --        -- to configure manually:
  --        -- config = function
  --        --   require'zotero'.setup{ <your options> }
  --        -- end,
  --      },
  --    },
  --    config = function()
  --      local telescope = require("telescope")
  --      -- other telescope setup
  --      -- ...
  --      telescope.load_extension("zotero")
  --    end,
  --  },
}
