font: "HasklugNerdFont 13"
background: "#31353f"
color: "#abb2bf"
border: "#98c379"
separator: "    ➜ "
border_width: 2
corner_r: 0
padding: 15
rows_per_column: 6
column_padding: 25
anchor: bottom
inhibit_compositor_keyboard_shortcuts: false
auto_kbd_layout: true

menu:
  # Spawning: {{{
  # Inputs: {{{
  - key: ";"
    desc: "󰍿 Toggle Inputs"
    submenu:
      - key: "a"
        desc: " Toggle Trackpad"
        cmd: "toggle-trackpoint 'Synaptics TM3075-002' 󰟸"
      - key: "k"
        desc: " Toggle Keyboard"
        cmd: "_keyboard_toggle"
      - key: "o"
        desc: " Toggle Trackpoint"
        cmd: "toggle-trackpoint 'TPPS/2 IBM TrackPoint' 󰳽"
  # }}}
  - key: "f"
    desc: " Spawn Float"
    cmd: "qspawn --float 'wlr-which-key spawn.yaml'"
  - key: "g"
    desc: " Spawn New-Group"
    cmd: "qspawn --tab --level 1 'wlr-which-key spawn.yaml'"
  - key: "s"
    desc: " Spawn Split"
    cmd: "qspawn 'wlr-which-key spawn.yaml'"
  # Spliting: {{{
  - key: "S"
    desc: "󰃻 Split Position"
    submenu:
      - key: "h"
        desc: "󰤼 Split Left"
        cmd: "qspawn --split-x --pos previous 'wlr-which-key spawn.yaml'"
      - key: "j"
        desc: "󰤻 Split Down"
        cmd: "qspawn --split-y 'wlr-which-key spawn.yaml'"
      - key: "k"
        desc: "󰤻 Split Above"
        cmd: "qspawn --split-y --pos previous 'wlr-which-key spawn.yaml'"
      - key: "l"
        desc: "󰤼 Split Right"
        cmd: "qspawn --split-x 'wlr-which-key spawn.yaml'"
  # }}}
  # Tab: {{{
  - key: "t"
    desc: "󰓩 Spawn Tab"
    submenu:
      - key: "h"
        desc: "󰘌 Tab Prev"
        cmd: "qspawn --tab --pos previous 'wlr-which-key spawn.yaml'"
      - key: "l"
        desc: "󰘍 Tab Next"
        cmd: "qspawn --tab --pos next 'wlr-which-key spawn.yaml'"
      - key: "s"
        desc: "󰓩 Split Tab"
        cmd: "qspawn --tab 'wlr-which-key spawn.yaml'"
    # }}}
  # Tab new: {{{
  - key: "T"
    desc: "󰝜 Tab New"
    submenu:
      - key: "h"
        desc: "󰝜 Tab New Prev"
        cmd: "qspawn --tab --new-level --pos previous 'wlr-which-key spawn.yaml'"
      - key: "l"
        desc: "󰝜 Tab New Next"
        cmd: "qspawn --tab --new-level --pos next 'wlr-which-key spawn.yaml'"
      - key: "s"
        desc: "󰝜 Tab New"
        cmd: "qspawn --tab --new-level 'wlr-which-key spawn.yaml'"
    # }}}
# }}}

# vim: foldmethod=marker foldlevel=0
