#!/usr/bin/bash

BATTERY_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')
BATTERY_STATE=$(acpi -b| grep -P -o '[A-z]+(?=,)')

level0=$(echo "$BATTERY_LEVEL" | sed -n 1p)
level1=$(echo "$BATTERY_LEVEL" | sed -n 2p)
state0=$(echo "$BATTERY_STATE" | sed -n 1p)
state1=$(echo "$BATTERY_STATE" | sed -n 2p)

if [[ $level0 -lt 79 ]] && [[ $level1 -lt 79 ]]; then
    if [[ $state0 == "charging" ]] && [[ $state1 == "charging" ]]; then
        sudo tlp setcharge BAT0
        sudo tlp setcharge BAT1
        notify-send "Adapter Manager" "Charging battery" -i " " -u low
    else 
        sudo tlp setcharge 0 $level0 "BAT0"
        sudo tlp setcharge 0 $level1 "BAT1"
        notify-send "Adapter Manager" "On AC Power" -i " " -u low
    fi
else
    notify-send "AC SWITCH" "Already running default behaviour" -i " " -u low
fi
