#!/usr/bin/bash

export FZF_DEFAULT_OPTS_FILE=$HOME/.config/fzf/menu.conf
STATE=$(echo -e "Shutdown\nHibernate\nReboot\nSuspend\nLock" | fzf)

case $STATE in

    Shutdown)
        shutdown now
        ;;
    Reboot)
        reboot
        ;;

    Hibernate)
        systemctl hibernate
        ;;

    Suspend)
        systemctl suspend
        ;;

    Lock)
        brightnessctl -s && brightnessctl set 0% && xlock -mode blank && brightnessctl -r
        ;;
esac
