#!/usr/bin/bash

name=$(iwgetid -r)
ssh_port=220

if [[ $name == "XUAN DINH" ]] || [[ $name == "XUAN HANH" ]]; then
    ssh_port=22
else
    ssh_port=220
fi

alacritty -e ssh home -p $ssh_port -t $1

