local map = vim.keymap.set

map("n", "zp", function()
  vim.cmd("silent! mkview!")
  vim.cmd("normal! mq")
  vim.cmd("normal! zMzv")
  vim.cmd("normal! `q")
  vim.cmd("delmarks q")
  vim.cmd("silent! mkview!")
end, { desc = "Fold everything except current fold, preserve viewport" })

map("n", "zP", function()
  vim.cmd("silent! mkview!")
  vim.cmd("normal! mq")
  vim.cmd("normal! zMzvzczO")
  vim.cmd("normal! `q")
  vim.cmd("delmarks q")
  vim.cmd("silent! mkview!")
end, { desc = "Unfold at cursor, or levels below if already unfolded" })

map("n", "zc", "zc<cmd>silent! mkview!<CR>", { desc = "Close fold" })
map("n", "zC", "zC<cmd>silent! mkview!<CR>", { desc = "Close fold recursively" })
map("n", "zo", "zo<cmd>silent! mkview!<CR>", { desc = "Open fold" })
map("n", "zO", "zO<cmd>silent! mkview!<CR>", { desc = "Open fold recursively" })
map("n", "za", "za<cmd>silent! mkview!<CR>", { desc = "Toggle fold" })
map("n", "zA", "zA<cmd>silent! mkview!<CR>", { desc = "Toggle fold recursively" })
map("n", "zr", "zr<cmd>silent! mkview!<CR>", { desc = "Reduce folding" })
map("n", "zR", "zR<cmd>silent! mkview!<CR>", { desc = "Unfold all" })
map("n", "zm", "zm<cmd>silent! mkview!<CR>", { desc = "Fold more" })
map("n", "zM", "zM<cmd>silent! mkview!<CR>", { desc = "Fold all" })
map("n", "zb", "zb<cmd>silent! mkview!<CR>", { desc = "Scroll to bottom" })
map("n", "zt", "zt<cmd>silent! mkview!<CR>", { desc = "Scroll to top" })
map("n", "zz", "zz<cmd>silent! mkview!<CR>", { desc = "Scroll to center" })
map("n", "z.", "z.<cmd>silent! mkview!<CR>", { desc = "Scroll to cursor line center" })
map("n", "z<CR>", "z<CR><cmd>silent! mkview!<CR>", { desc = "Scroll to cursor line top" })
map("n", "z-", "z-<cmd>silent! mkview!<CR>", { desc = "Scroll to cursor line bottom" })

