# vim:fileencoding=utf-8:foldmethod=marker

include font.conf
include mouse.conf
include tuning.conf
include advanced.conf
include theme.conf
include layout.conf
include bar.conf
include keymaps.conf
include bell.conf
